create extension if not exists pgcrypto;

create table if not exists public.users(
 id uuid primary key default gen_random_uuid(),
 username text unique not null,
 password_hash text not null,
 is_admin boolean not null default false,
 created_at timestamptz not null default now()
);

create table if not exists public.questions(
 id bigint generated by default as identity primary key,
 title text not null,
 question_text text not null,
 answer text default '',
 explanation text default '',
 category text not null default 'GENERAL',
 image_url text default '',
 video_url text default '',
 code_content text default '',
 is_published boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.site_settings(
 id bigint primary key default 1,
 site_name text not null default 'MY QUESTION ARCHIVE',
 home_description text default 'أرشيف شخصي لمساعدة الطلاب على حل وفهم الأسئلة التعليمية.',
 gate_description text default 'أدخل اسم المستخدم وكلمة المرور للوصول إلى الأرشيف.',
 intro_background text default '',
 whatsapp text default '', telegram text default '', email text default '',
 updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages(
 id bigint generated by default as identity primary key,
 username text not null,
 sender_role text not null check(sender_role in('student','admin')),
 message text not null,
 created_at timestamptz not null default now()
);

create table if not exists public.reports(
 id bigint generated by default as identity primary key,
 question_id bigint references public.questions(id) on delete set null,
 username text default '',
 message text not null,
 created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.questions enable row level security;
alter table public.site_settings enable row level security;
alter table public.chat_messages enable row level security;
alter table public.reports enable row level security;

drop policy if exists "public questions" on public.questions;
create policy "public questions" on public.questions for select to anon,authenticated using(is_published=true);

drop policy if exists "public settings" on public.site_settings;
create policy "public settings" on public.site_settings for select to anon,authenticated using(true);

drop policy if exists "public reports" on public.reports;
create policy "public reports" on public.reports for insert to anon,authenticated with check(true);

insert into public.site_settings(id) values(1) on conflict(id) do nothing;

insert into public.users(username,password_hash,is_admin)
values
  ('archiveadmin','56e03cd1edf98f331fbe5e7631dde3a964674231f07991909df50f2f8fe06547',true),
  ('student001', 'be89e3657d86d7a6397ce8e3dc2edc473f86f219fdf8aae1c33fd74d1715b7cd', false),
  ('student002', '462b7edb3af117b68729e119efc2c6b2553641c6dd51a40a9e506b8380d1c4a3', false),
  ('student003', '2618c14d75a2b3149ffc4c16d96240fc8908dc6232332e7470df8a8c96b4570d', false),
  ('student004', '047523ab8ef1ed644c3bbe8ae020aafb23aeb69c2ea3bebe687ceb5b4710d7bb', false),
  ('student005', '7a2b89bbb9536e9833ec8caf87c3f8614106cc0444625181d429377bc7664fb5', false),
  ('student006', 'cde85d915f981f2311f31eb4393ae7878799c2a1b52fb8befa7db41ab4a3a51d', false),
  ('student007', '59409695d9d6df1a62beeba569c9cac931410dd24917aa0e26708d4534555474', false),
  ('student008', 'ffa0c16df2c65bf5e9994880f38e596c221c1278b1c71ba29a601cd40660439f', false),
  ('student009', '2c245f8845e1ec44cf80b9e72f0c63c87389748f0a4975786b464426772d7dba', false),
  ('student010', '296896185ade13063b4bd4f2938ad751c90ce1461fe06ba1688e32b1dd946cb0', false),
  ('student011', '0be4386ddfebf36a9aa5b8c78db8e67e3c298e2a1cf3540f097a74dc09242f51', false),
  ('student012', '31e90b1e683e50be6c5b1abdd268ec1b121fc571706f0e9100006afd7e4c5050', false),
  ('student013', '2a90497bc3f191741132831e595a79abba0c5c699079320ae1a6522de9e13e29', false),
  ('student014', '71bcae1a386b26f57c82f1103a6a87cacd079f246f17c0955dea008e3b2a8ec0', false),
  ('student015', 'c4029befed425e0e2036f670304e55cc1e5aec528bdd383433af7b2ac45674a1', false),
  ('student016', '3d3f7d35de9d478bec3232d93355965ca60dcef2a802752661da477770c27b79', false),
  ('student017', 'e22cfef1231e672d529bed5f76f8400765b9748c81dc86c7ddcf40d1847dd200', false),
  ('student018', 'f148db6f7d09712f07b9e33389cd142aaa8af12899c52d1b3ebc958ed6923a87', false),
  ('student019', 'a85b2c3d0cd72221d5a181e2bc27570cca13d07ae8ef67ab15c9c20de45d2a13', false),
  ('student020', 'c9083128fa9a83b15a1c01b706c86053457037b28c730e59bf36bf4eb8dc5040', false),
  ('student021', 'bdcdb5eaaa86df3c9b5d5fd54bd872e39631a63a134e3f4442dfde075dd83ade', false),
  ('student022', '0fa17e991bea8c928b50fd6dbf214d919dc4363ec741da0c24cbe416a5ad76c2', false),
  ('student023', '9e738e5ddaf214217b48a7611eb31e3270f6faacef9f7deb2671dd59f759ee3f', false),
  ('student024', 'c2f4f74a952514bc3eb03f74abb20d5f1185a5a75a52cfe8a44a0977548bac35', false),
  ('student025', 'aabb059cd290e38bb18afd057c0f6fba88cd03510420bef9b4455a97ff0479f1', false),
  ('student026', 'd2989e7d1796670aa979666fa14a6ded1c75d278c3378fbda40dcab2644c535c', false),
  ('student027', '4fe55ba3910eda40502dcd2524bae08b375a85f979d1183b4c94d3b3c2a473e5', false),
  ('student028', '4b4d89527520345bf46be5c803dc3cf6bc47eccf256d04f8bbee699a0104448b', false),
  ('student029', '544e3e384541be7801cfbc9ac3199ec0416e9e2120bb71a144e3c50e23bbb2fb', false),
  ('student030', 'bc179485e35f1f158e9280fbbba342bf1de11c9e2df8d5e5b03e7002d483cf2a', false),
  ('student031', 'e1ce63449cb106acd908f0dac5ac6ccf3dce4023f9fbb2424352b4987319e0e7', false),
  ('student032', 'a0dfaca69de100c194fee2fafdadd67c38085c8e71d14968639ac8aba12c7d4d', false),
  ('student033', 'cae03d7e1cac7c8c14c07b8e42c7e74957e4a1eefa255d664672c2e17b18d61c', false),
  ('student034', '0ae8762cbd0755f8c40049332f0b0580406e8bfae47aec17fd2d105501aabca7', false),
  ('student035', '15ae78c112841261e3d7e1fdb5ff116e644726217944eb09c7950b6bd97b5e4b', false),
  ('student036', '239dd2be6c52944a387bc6281d25d1a9c3f168b1911f0293a28fbbad7f3e6128', false),
  ('student037', '931bc331fbced88aa32efd3bb01ee8c12e4345c5df1a2b0804c980209e946702', false),
  ('student038', '043c01a635294598a4bb4656638412670e238d053bede10276a9cf48309cc089', false),
  ('student039', 'e9a1ad76140dd8e516f394270c85cb3ba722a175fad35621ee5c58e12584b670', false),
  ('student040', '41d1d7c0b9aafe231d1364416459247536665934881d2f033841e5422877db2a', false),
  ('student041', '6ab518075994a777bf7a2ecdff20716a80731ec1415e2acd526069736fb79e2f', false),
  ('student042', '8d9ebdba3d02db59ec9bbbbb8ab1697011d5b55f268e7b6b353a033adf6f78dc', false),
  ('student043', 'a0c32fb49de3e0e928145a2b87a8fc1937e43d47866c78c872382e9e9311fdcb', false),
  ('student044', 'c74553790b002a91b011501d0b4edd06a60e28053d12f6b2c646819a5408a283', false),
  ('student045', '4cbf0cab8e55dfed4ea17c793f4b719f649789f951ec5f874a9e05c8c34a0ee2', false),
  ('student046', '398c0a9811e7b453c2d24af937d102d3d80027ea125032f0a710173bf0e2fdce', false),
  ('student047', 'af5c7d1aa9d0c2966682891e592e95e5b1d9f44ac8a717ed7ea433258908658a', false),
  ('student048', '550615561d7176402c7ec31a98cd8cb064479654b9f5ad35cddef6e90741297d', false),
  ('student049', '348f850589a172fa1bf2db8290d066b7001ad12a6d31825354ab174305f18281', false),
  ('student050', '5b89f06048f7765d40cefdfbc02fc7e41ec524f1003f152826e05cc068d91f55', false),
  ('student051', '72fb013e0d0278f5138e07bf6fabd8285ec5b7443bcd25a52253233c0ab16f49', false),
  ('student052', '535121a2066266481f6814623dbdd056b986a55f91befff0428155d3dc131150', false),
  ('student053', '9868b52df9662a1cd80d6d759d1788a31b6fa3bc848ce828ba1b086e9b358c7d', false),
  ('student054', '6e1254923c57132cb0288c51e88bc4a4377c0e32888aa796b36a7c8f35b620d8', false),
  ('student055', 'fdf90304786b50b96ca43304d57a4822708b8799c2630612e971b90ef1859f76', false),
  ('student056', 'e6d559d195dd9c568b2aebd366c41c0f25174286ec8b5062f9854bd5cfe33a77', false),
  ('student057', 'd5e34c34e797e4f92323259fb1bf596b6c6aa26ce6d6e43f160d16263513c7a5', false),
  ('student058', '6b5114b5dd41c064e016c7a62d78c23e8a0e8ad30d04bb11a156348b20d32066', false),
  ('student059', 'cc0954ed8ec939d2fbc225a5d0fe3f6c7b22ae68baeda07279ed5134b1ed8e30', false),
  ('student060', '26bdf766ac7560f2a9ceb0ddf569a3ce304812cad320f6cf4b695e1cec2d461c', false),
  ('student061', '2e59b674d6211bc714aff53cc43460d8374312a5ae3227e1b43f072962235dd2', false),
  ('student062', 'd174ccb26d7c6970319da5551a9b6a3eb5b1e29a3ff9ad7c806150acb86db3b6', false),
  ('student063', 'a60a72f4257e97575b302c3dea8cb09724da2323891483df6d5a7cf4c289c7f8', false),
  ('student064', 'f0dd9c1165554d47c7e6d567b7989b16bd70d0276723c0616fbb31d6788ce276', false),
  ('student065', 'cac00ca89526373d44131fdac11b560fb3dea0407c8f4c1436b436efdde020eb', false),
  ('student066', '46dd988929ec4d7a0a882eb61f4a1771c80dd2214c008581525fbfc263f06571', false),
  ('student067', '4e5907ca471d425583d2c7a7547479e66168b2fe49be77a1e5a103304260ff69', false),
  ('student068', 'de00e1819f028d08669025320245bdca67d46c5e805709064ad496200454bef6', false),
  ('student069', '2b844024de42eb19c5d22107ae40c965ec2f6cc3070d898fb7f5e0be36f3bcfa', false),
  ('student070', '8b29df7f3e3a2589ba4871161648f32b070428c4169d8bdf21276f0406e18765', false),
  ('student071', 'a98a538b124c54708fb8cfdc89f792237ea1ee3a6e599b293bb53288a60d4954', false),
  ('student072', '751fb72cd581f664217b7013499592a5f16dab086a16f389c7913684de7f3e7b', false),
  ('student073', '95632ea78d4d3d503b33ac478ac9b071511cf346e0688215d9d2adaea91396cc', false),
  ('student074', 'dfd093a4f94deeddfa2dcadc6d0b37e3b59fee033cfa3bb63185ac9c908b3b62', false),
  ('student075', '352215fc3aa45bb4e52fb6fb617d2eca8246efd25b2405a05ccd8327bca1cefe', false),
  ('student076', 'bf09c7ba347e7ac04bd9028929b3d1efcf4b0bd8a0b46ce1a8e0c8d6c4ebc98b', false),
  ('student077', '1467d8198c936afc489aa36524ca484febf8fe01177bae217827c4c684b15775', false),
  ('student078', 'f4969538c30398f7bfd7b977e262208ae79600fe26814e84d13e05635d317857', false),
  ('student079', '3b90feccf67366ae3c67817522453a7ee3864ab2b5e2967b19e62b6b96bdc95c', false),
  ('student080', '90ec070bb33e71893e98d3c0b0b26b6620d3ed614b46d058c66884d22f6710f0', false),
  ('student081', '924e75593c9ae67cc44f66a7f48c6b38383ae20a7122e3ce026775145066a6da', false),
  ('student082', '8a869a947805e7aacd6e900a86c7e6b85d72e35dbd96caebc43bd329516e37dd', false),
  ('student083', 'eb0b47e6a2ec837b5a0f7a720a7ff34f9dcc50e3f770d4ef97ee6861a52c36a6', false),
  ('student084', 'd101e7530f5f67669ddec179e2b1787200fb760e3ce4de7b36a13c6de541b4e7', false),
  ('student085', '924c9fc450c8ae07a79239b4b8cd6697c18ae207faf51b3a7cb341545ccfc347', false),
  ('student086', '4a9fce20c9fd0f8de72cfdd6c1bae1728bd4f9cc77c117a6eae52e4c7f13b8e1', false),
  ('student087', '7b77ce7a556c67b2edfcab4393daf168b51d9e1e262be064767836aab3d45fc9', false),
  ('student088', '518fb353398e6ae5f016a5593cc2210357768c47ba0689f5c264774fdd6cb9da', false),
  ('student089', '0595ea8fbf03e65ef375f8f7add9beb3a971f8a5160650999b46796e019ff53b', false),
  ('student090', '4efa7eeb441c804542c06a1d81d4a4aa3818123884a8c6e0714b6ee27c77d300', false),
  ('student091', 'fa3d38a1268e6af4c5f6fd61f63c564f2b5e7e62cf34d6f2603db5bdd651b8ed', false),
  ('student092', '48db447b27b686695e1ac75806070ebbb49783904c2b2692f59675ca5a92ba9e', false),
  ('student093', '27ba97e9f044f0fa9e1727725ff0894966429ed12176a18c92e3553c517e3c38', false),
  ('student094', '14909974371ccb88fe75b90c5d9f7062f1093dd60282cd108a27a8dc8549ed27', false),
  ('student095', '05fd6ef3f1abebea68b149b640b669b75a62487e1bdb550ff6b5aec950f2c0cd', false),
  ('student096', 'e8a8d399da3306f1409e517d05a4efb89e0dc28726ae06a1fb80292397f3af8b', false),
  ('student097', '388e7ae1008a506585570e0b96b181f5edb5cb91a2f53930136ed94d04cc55f4', false),
  ('student098', '845da7d4c114d5dc2715eea9d6e19217adc7d1af13df8ee4ef12ef72225ebcb6', false),
  ('student099', '5249b2d56868672bedf2aa56593c23b458e5d2fa0e14fb56f849bf6de939bc5b', false),
  ('student100', '42ba5cef7d665d6f375b80be2a2ad6698097b387a6f0cce75c3fd5ef06609418', false),
  ('student101', '9d2209210d26415a7a48080982aecb8d484cdffc0596e32f4b8c1cf01292662d', false),
  ('student102', '88c982e4c62e8871c8f7d6adf8d01ee05f097e1920168dad88415020b899a565', false),
  ('student103', 'cbd54ae0bddcc8cca446829e985e88a91d093293e52c10fd42d32507671d492c', false),
  ('student104', '65436c4df964937b6a0146f76bd4a103aa10d040abc2f61a5850a8f0584e7ac1', false),
  ('student105', '78dafd5cbc7cf86b3f12454130e60d3a2fdbd69885b7fe1940f07ddcdf7c7a16', false),
  ('student106', 'fe44df3a5ef7d7aa49e55878786a6e0aaeefaf09ba6c1ab43ceb4405febed28b', false),
  ('student107', '3ed957967be73648438599892c44f991ebe5fcd0243d03967ea3b1d5091631b9', false),
  ('student108', 'bc42152c1aaecae0cdc25d3c56c591bd8da68191d41861407567b410182b4934', false),
  ('student109', 'e8d0b34f751d2d396a1d2a2da69b9b6e4433ca38aa30164a1ee38e9771c32d48', false),
  ('student110', 'de45eb7417b339648a34071fdcd64a150e5ec424012f1e3aa719e78120aababe', false)
on conflict(username) do nothing;
